// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PeerReviewMVC.Data;

namespace PeerReviewMVC.Migrations
{
    [DbContext(typeof(PeerReviewContext))]
    [Migration("20191021133822_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PeerReviewMVC.Models.Assignment", b =>
                {
                    b.Property<int>("AssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DraftDue");

                    b.Property<DateTime>("EvalDue");

                    b.Property<int?>("EvalGuideRubricId");

                    b.Property<string>("FileName");

                    b.Property<DateTime>("FinalDue");

                    b.Property<int?>("GroupId");

                    b.Property<string>("Text");

                    b.Property<string>("Title");

                    b.HasKey("AssignmentId");

                    b.HasIndex("EvalGuideRubricId");

                    b.HasIndex("GroupId");

                    b.ToTable("Assignment");
                });

            modelBuilder.Entity("PeerReviewMVC.Models.Evaluation", b =>
                {
                    b.Property<int>("EvaluationId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("SubmissionId");

                    b.Property<string>("Text");

                    b.HasKey("EvaluationId");

                    b.HasIndex("SubmissionId");

                    b.ToTable("Evaluation");
                });

            modelBuilder.Entity("PeerReviewMVC.Models.Group", b =>
                {
                    b.Property<int>("GroupId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("GroupId");

                    b.ToTable("Group");
                });

            modelBuilder.Entity("PeerReviewMVC.Models.Rubric", b =>
                {
                    b.Property<int>("RubricId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("RubricId");

                    b.ToTable("Rubric");
                });

            modelBuilder.Entity("PeerReviewMVC.Models.Submission", b =>
                {
                    b.Property<int>("SubmissionId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AssignmentId");

                    b.Property<string>("FileName");

                    b.Property<string>("Text");

                    b.Property<DateTime>("submitted");

                    b.HasKey("SubmissionId");

                    b.HasIndex("AssignmentId");

                    b.ToTable("Submission");
                });

            modelBuilder.Entity("PeerReviewMVC.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("GroupId");

                    b.Property<string>("Name");

                    b.Property<int?>("SubmissionId");

                    b.HasKey("UserId");

                    b.HasIndex("GroupId");

                    b.HasIndex("SubmissionId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("PeerReviewMVC.Models.Assignment", b =>
                {
                    b.HasOne("PeerReviewMVC.Models.Rubric", "EvalGuide")
                        .WithMany()
                        .HasForeignKey("EvalGuideRubricId");

                    b.HasOne("PeerReviewMVC.Models.Group")
                        .WithMany("Instructions")
                        .HasForeignKey("GroupId");
                });

            modelBuilder.Entity("PeerReviewMVC.Models.Evaluation", b =>
                {
                    b.HasOne("PeerReviewMVC.Models.Submission")
                        .WithMany("Evaluations")
                        .HasForeignKey("SubmissionId");
                });

            modelBuilder.Entity("PeerReviewMVC.Models.Submission", b =>
                {
                    b.HasOne("PeerReviewMVC.Models.Assignment")
                        .WithMany("Submissions")
                        .HasForeignKey("AssignmentId");
                });

            modelBuilder.Entity("PeerReviewMVC.Models.User", b =>
                {
                    b.HasOne("PeerReviewMVC.Models.Group")
                        .WithMany("Users")
                        .HasForeignKey("GroupId");

                    b.HasOne("PeerReviewMVC.Models.Submission")
                        .WithMany("Users")
                        .HasForeignKey("SubmissionId");
                });
#pragma warning restore 612, 618
        }
    }
}
